### ISSUE TITLE
Different behaviors between Sequence and System diagrams

### ISSUE THREAD

**Issue by rafaelverger** [CodeRecipe-dev/ServerlessChatroomAWS-GCP#1]
`sendMessage` execution have different approaches in each diagrams... In Sequence diagram first u send message to GCP Sentiment analysis and then go to AWS Dynamo to handle connections, but in System diagram this order is inverted

**Comment by CodeRecipe-dev** [comment]
Thanks for pointing this out, the correct sequence is first analyze the sentence, then get who to broadcast to in connectionStore, then broadcast. The order in seq diagram is correct and I have changed the sys diagram to match that. 

Thanks for your feedback

**Comment by CodeRecipe-dev** [comment]
closing it now
